[phases.setup]
nixPkgs = ["ffmpeg", "python310"]

[phases.build]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
