[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
commands = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "/app/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"

