[phases.setup]
nixPkgs = ["ffmpeg", "libsndfile"]   # <- important for moviepy/librosa

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[processes]
web = "uvicorn main:app --host 0.0.0.0 --port $PORT"
