[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
commands = [
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"

